FROM container-registry.oracle.com/os/oraclelinux:8

COPY rpms /tmp/

RUN dnf install -y /tmp/*.rpm &&\
    rm -rfv /var/cache/yum /tmp/* /LICENSES &&\
    ln -s /usr/share/licenses /LICENSES

FROM container-registry.oracle.com/os/oraclelinux:8-slim

COPY --from=0 /bin/operator /usr/local/bin/operator

COPY LICENSE THIRD_PARTY_LICENSES.txt /usr/share/licenses/

USER 1001

ENTRYPOINT ["/usr/local/bin/operator"]
